### ISSUE TITLE
How to use MIND package.

### ISSUE THREAD

**Issue by saeedfc** [randel/MIND#7]
Hi,
I am really excited to use this tool. However, I am a bit confused about the parameters and the kind of input required.
hence I kindly request your comments on the following. A vignette with examples of input data would be much appreciated.

###  What I have:-
1) Single Cell Reference Data (as a Seurat Object) coming from 10 patients. (Combined with case and control, I can split them easily though if required to run **MIND** and construct separate gene expression matrices)
2) Bulk RNA seq expression Matrix (Gene X Sample matrix) from 50 patients.

### What I have to do:-
1) Use **_get_prior_** function to generate a  CTS prior profile matrix from the combind (case and control) single cell data.
2) Run **_bMIND_** where I intend to use Bisque for deconvolution.
Arguments that are not clear:-
1) **_Sample_ID_** (colnames of my Bulk RNA seq expression Matrix?)
2) **_profile_** (Output of the 1st step (**_get_prior_**)?)
3) **_covariance_** (From Output of the 1st step (**_get_prior_**)?)

4) Then there is **profile_co**, **covariance_co** .. etc for controls and cases separately. In my case, what can I do here? My single cell data is combined. If necessary I can split i into two matrices of case/control. After I have separate gene exp matrix for each condition, should I run _**get_prior**_ for each of them? and use the output here?
5) Also how can I deal with the argument **'y'** in this case? Does it refer to the samples of the bulk (whether they are case/ control)? In that case how is it dfferent from **_case_bulk_** at the end?
6) Also for the 'covariate' related arguments, can you please provide some examples of usually used covariates, or how covariate matrix look?
7) **_noRE_** (Can I use this argument to get a single deconvoluted matrix for the whole bulk data?-If thats what I would prefer?)
8) _**np**_ (What is non informative prior?)
9) **_max_samp_** (Is there a default value that I can use or should I try different values?)

Thanks and Kind regards,
Saeed

**Comment by randel** [comment]
Thanks for your interest! Please see a tutorial here. https://htmlpreview.github.io/?https://github.com/randel/MIND/blob/master/bMIND_tutorial.html

My responses are below.
3. Sample_ID (colnames of my Bulk RNA seq expression Matrix?)
Yes, if there are no repeated measures per subject. bMIND will take bulk colnames by default.

4. profile (Output of the 1st step (get_prior)?)
5. covariance (From Output of the 1st step (get_prior)?)
yes

6. Then there is profile_co, covariance_co .. etc for controls and cases separately. In my case, what can I do here? My single cell data is combined. If necessary I can split i into two matrices of case/control. After I have separate gene exp matrix for each condition, should I run get_prior for each of them? and use the output here?
yes

7. Also how can I deal with the argument 'y' in this case? Does it refer to the samples of the bulk (whether they are case/ control)? In that case how is it dfferent from case_bulk at the end?
If there are no repeated measures per subject, the two are the same. `y` would correspond to each subject if there are repeated samples per subject.

8. Also for the 'covariate' related arguments, can you please provide some examples of usually used covariates, or how covariate matrix look?
Examples would be age or sex. It is sample by covariates.

9. noRE (Can I use this argument to get a single deconvoluted matrix for the whole bulk data?-If thats what I would prefer?)
If your goal is for CTS-DE, there is no need to estimate sample-level CTS expression since CTS-DE is built-in. noRE = F is used in case sample-level CTS is needed.

10. np (What is non informative prior?)
By default, non-informative prior has a variance of 1e10 for mean expression and nu = 0 in inverse Wishart prior for variance parameters.

11. max_samp (Is there a default value that I can use or should I try different values?)
The default should work.
